[build]
  functions = "netlify/functions"
  publish = "."   

[[redirects]]
  from = "/loteria/*"
  to = "/loteria/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200